org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/develop)

minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=18.2-26.2
maven_group=com.example
archives_base_name=xiaohe66-meteor-lotus

# Dependencies

fabric_api_version=0.154.2+26.2

# Meteor (https://maven.meteordev.org)
meteor_version=26.2-SNAPSHOT

# Baritone (https://maven.meteordev.org)
baritone_version=26.2-SNAPSHOT

malilib_version = 0.29.6

litematica_version = 0.28.8