org.gradle.jvmargs=-Xmx2G

# Fabric Properties (https://fabricmc.net/develop)

minecraft_version=26.1.2
loader_version=0.18.4

# Mod Properties
mod_version=18.2-26.1.2
maven_group=com.example
archives_base_name=xiaohe66-meteor-lotus

# Dependencies

fabric_api_version=0.149.1+26.1.2

# Meteor (https://maven.meteordev.org)
meteor_version=26.1.2-SNAPSHOT

# Baritone (https://maven.meteordev.org)
baritone_version=26.1-SNAPSHOT

malilib_version = 26.1.2-0.28.6

litematica_version = 26.1.2-0.27.6